### PR TITLE
more params on the BuyNow request

### PR DESCRIPTION
**Pull request by cconstantin**
I had this done a few days ago, but I didn't have time to thoroughly test it. I'm sending it to you now so we don't do the same work twice.

### CODE REVIEW

**Comment by axefrog** [comment]
The options fields, I notice you have them going from 0 to 6. is 6 an arbitrary number you chose or is this PayPal's option limit?

**Comment by axefrog** [comment]
Just looking at the code some more. Part of the goal of the library is to make implementation a little more intuitive than what PayPal provides and translate what we implement back into PayPal's messier format. For instances where PayPal provide a method of specifying an arbitrary number of something (e.g. dropdown options or shopping cart items), I would suggest creating a simple class to contain the properties of a single unit, then providing a collection whereby instances of the class can be added and removed. The GetValues() method would worry about the translation back to PayPal's format and hide it from the developer. Also, I'd suggest for property names such as "Os2" that you've specified, a friendlier name would be better. Again, the idea is to make the library friendly for developers and hide them from PayPal's unintuitive API and interfaces.

**Comment by cconstantin** [comment]
All of these are good principles and suggestions. The main reason I didn't spend the time to implement something similar with what you suggested is that I do not understand very well how all those parameters are used. I thought it better to add them in a raw form for now, so at least they are accessible, until such time that I figure out what the best abstraction for them is.

**Comment by axefrog** [comment]
Sorry forgot to write back. Hit me up on googletalk (axefrog@gmail.com) or Skype text chat (axefrog) some time if you want to discuss the PayPal variables or whatever. I've built about 3-4 applications that use them, so while not comprehensive by any stretch of the imagination, I have a good idea of what a lot of the variables mean and how they work.

**Pull request closed without merging**
